Repository pyronear/pyro-engine, pull requests merged in 2021-06, with the labels that each got.

#31 Add security
  server/src/app/api/deps.py
  server/src/app/api/routes/inference.py
  server/src/app/api/routes/login.py
  server/src/app/api/routes/metrics.py
  server/src/app/api/schemas.py
  server/src/app/api/security.py
  server/src/app/config.py
  server/src/app/main.py
  server/src/requirements.txt
  server/src/tests/conftest.py
  server/src/tests/routes/test_inference.py
  server/src/tests/routes/test_metrics.py
Labels: enhancement, route: login, security

#50 Update engine
  pyroengine/engine/engine.py
  server/src/app/api/routes/inference.py
  server/src/config_data.json
  server/src/pi_zeros_data.json
Labels: enhancement

#47 Add update rooter module
  pyroengine/pi_utils/reboot_router.py
  server/src/requirements.txt
Labels: enhancement

#54 update docker
  requirements.txt
  server/src/Dockerfile
  server/src/requirements.txt
Labels: bug

#55 Map hostnames
  pyroengine/pi_utils/.env
  pyroengine/pi_utils/.env.dist
  pyroengine/pi_utils/ip_hostname_mapping.py
  server/data/config_data.json
  server/data/ip_hostname_mapping.json
  server/data/pi_zeros_data.json
  server/docker-compose.yml
  server/src/app/api/routes/inference.py
  server/src/config_data.json
  server/src/pi_zeros_data.json
Labels: bug

#56 add check connection script
  pyroengine/pi_utils/check_connection_pizero.sh
Labels: enhancement
