Repository pyronear/pyro-engine, pull requests merged in 2021-09, with the labels that each got.

#60 chore: Updated requirements.txt
  main.rpi.requirements.txt
  requirements.txt
Labels: topic: build

#63 Switch to script
  pyroengine/pi_utils/reboot_router.py
Labels: bug

#61 feat: Added an alert cache mechanism to avoid loosing information without internet
  pyroengine/engine/engine.py
  pyroengine/engine/predictor.py
  requirements.txt
  test/test_engine.py
Labels: enhancement, topic: build, route: inference

#65 Improved router reboot script
  pyroengine/pi_utils/check_internet_connection.sh
Labels: invalid
