Repository pyronear/pyro-engine, pull requests merged in 2021-04, with the labels that each got.

#15 Local api for api devices based on Fastapi
  server/README.md
  server/docker-compose.yml
  server/src/Dockerfile
  server/src/app/api/routes/inference.py
  server/src/app/api/routes/metrics.py
  server/src/app/api/schemas.py
  server/src/app/config.py
  server/src/app/main.py
  server/src/requirements-dev.txt
  server/src/requirements.txt
  server/src/tests/__init__.py
  server/src/tests/conftest.py
  server/src/tests/routes/test_inference.py
  server/src/tests/routes/test_metrics.py
Labels: enhancement, route: inference, route: metrics

#16 Test patch
  requirements.txt
  test/fake_gpiozero.py
  test/pi_patch.py
  test/test_raspberryPi_monitorPi.py
Labels: bug

#23 add .nojekyll file
  .nojekyll
Labels: documentation

#19 Changes in pyro-engine for rpi
  .gitignore
  main.rpi.requirements.txt
  pyroengine/engine/predictor.py
  pyroengine/pi_utils/.env.dist
  pyroengine/pi_utils/camera.rpi.requirements.txt
  pyroengine/pi_utils/monitor_pi.py
  pyroengine/pi_utils/requirements.txt
  server/src/requirements.txt
  test/test_raspberryPi_monitorPi.py
Labels: enhancement

#21 fix: Forced frame to RGB mode
  pyroengine/engine/engine.py
Labels: bug

#22 add demo script to readme
  README.md
Labels: documentation

#24 Allow webserver pyroengine use
  server/docker-compose.yml
  server/src/Dockerfile
Labels: enhancement

#25 Solve vision dependencies compliance - alpine to slim docker image
  server/src/Dockerfile
  server/src/requirements.txt
Labels: enhancement

#29 update badges
  README.md
Labels: documentation

#30 chore: Add workflow to publish docker image
  .github/workflows/publish-docker-image.yml
Labels: enhancement

#20 Inference using engine
  pizero/runner.py
  server/docker-compose.yml
  server/src/Dockerfile
  server/src/app/api/routes/inference.py
Labels: enhancement

#33 create env file and remove not used import
  README.md
  pizero/python.env.dist
  pizero/runner.py
  pyroengine/pi_utils/.env.dist
  pyroengine/pi_utils/monitor_pi.py
Labels: enhancement, question

#34 Refacto pizero directory into file in pi_utils and update consequently
  README.md
  pizero/python.env.dist
  pyroengine/pi_utils/camera.rpi.requirements.txt
  pyroengine/pi_utils/monitor_pi.py
  pyroengine/pi_utils/runner.py
Labels: enhancement

#35 Add network in docker-compose to allow for use under OpenVPN
  server/docker-compose.yml
Labels: bug, enhancement

#36 Rewrite of runner.py to make it similar to monitor_pi.py
  pyroengine/pi_utils/runner.py
  test/fake_picamera.py
  test/pi_patch.py
  test/test_runner.py
Labels: enhancement, question
