Repository pyronear/pyro-engine, pull requests merged in 2022-07, with the labels that each got.

#79 black formatting
  .github/validate_headers.py
  docs/source/conf.py
  pyroengine/pi_utils/ip_hostname_mapping.py
  pyroengine/pi_utils/pi_zeros/monitor_pi.py
  pyroengine/pi_utils/pi_zeros/runner.py
  scripts/collect_env.py
  server/src/app/api/routes/inference.py
  server/src/app/api/routes/metrics.py
  server/src/app/api/routes/write_image.py
  server/src/app/api/schemas.py
  server/src/app/config.py
  server/src/app/main.py
  server/src/tests/routes/test_metrics.py
  setup.py
  test/fake_gpiozero.py
  test/fake_picamera.py
  test/pi_patch.py
  test/test_engine.py
  test/test_raspberryPi_monitorPi.py
  test/test_utils.py
Labels: enhancement

#82 fix version
  requirements.txt
Labels: bug

#83 setup ci
  .github/workflows/main.yml
  .github/workflows/pi.yml
Labels: enhancement

#84 fix version
  requirements.txt
Labels: bug

#80 Drop useless files
  pyroengine/pi_utils/check_internet_connection.sh
  pyroengine/pi_utils/ip_hostname_mapping.py
  pyroengine/pi_utils/monitor_pi.py
  pyroengine/pi_utils/pi_zeros/__init__.py
  pyroengine/pi_utils/pi_zeros/check_connection_pizero.sh
  pyroengine/pi_utils/pi_zeros/monitor_runner.sh
  pyroengine/pi_utils/pi_zeros/requirements.txt
  pyroengine/pi_utils/pi_zeros/runner.py
  pyroengine/pi_utils/reboot_router.py
  test/test_raspberryPi_monitorPi.py
  test/test_runner.py
  test/test_utils.py
Labels: invalid

#78 Feature/switch to reolink cam
  pyroengine/engine/engine.py
  pyroengine/pi_utils/update_script.sh
  runner/docker-compose.yml
  runner/src/Dockerfile
  runner/src/runner.py
  server/README.md
  server/data/pi_zeros_data.json
  server/docker-compose.yml
  server/src/Dockerfile
  server/src/app/api/routes/inference.py
  server/src/app/api/routes/metrics.py
  server/src/app/api/routes/write_image.py
  server/src/app/api/schemas.py
  server/src/app/config.py
  server/src/app/main.py
  server/src/requirements-dev.txt
  server/src/requirements.txt
  server/src/tests/__init__.py
  server/src/tests/conftest.py
  server/src/tests/routes/test_inference.py
  server/src/tests/routes/test_metrics.py
  server/src/tests/routes/test_write_image.py
Labels: enhancement

#85 fix: Fixed dockerfile
  Dockerfile
Labels: bug, topic: build

#86 typo
  Dockerfile
Labels: bug

#87 Feature/set crontab
  scripts/check_internet_connection.sh
  scripts/update_script.sh
Labels: invalid

#88 remove matplotlib
  requirements.txt
Labels: bug, invalid

#90 fix variable name
  runner/src/runner.py
Labels: bug

#91 fix variable name (#90)
  runner/src/runner.py
Labels: bug

#92 save img for debug
  runner/src/runner.py
Labels: enhancement

#93 Bugfix/get image
  runner/src/runner.py
Labels: bug

#94 improve logs
  pyroengine/engine/engine.py
Labels: enhancement

#95 Feature/capture
  runner/src/capture.py
  runner/src/runner.py
Labels: invalid

#96 fix update script
  scripts/update_script.sh
Labels: bug

#99 define prob if no pred
  pyroengine/engine/engine.py
Labels: bug

#97 ignore config data
  .gitignore
Labels: invalid

#100 docs: Updated funding
  .github/FUNDING.yml
Labels: documentation
