Repository pyronear/pyro-engine, pull requests merged in 2023-04, with the labels that each got.

#149 update header
  docs/source/conf.py
  pyroengine/core.py
  pyroengine/engine.py
  pyroengine/sensors.py
  pyroengine/utils.py
  pyroengine/vision.py
  setup.py
  src/capture.py
  src/run.py
Labels: topic: ci

#150 fix black
  pyroengine/engine.py
  setup.py
  tests/test_core.py
  tests/test_engine.py
  tests/test_sensors.py
  tests/test_vision.py
Labels: topic: ci

#151 Update README.md
  README.md
Labels: ext: docs

#152 Promtail
  README.md
  docker-compose.yml
  promtail/config.yml
Labels: type: enhancement, type: new feature

#153 analyze stream timeout
  pyroengine/core.py
  src/run.py
Labels: type: bug

#154 update docker img
  Dockerfile
Labels: invalid

#155 add utc
  pyroengine/engine.py
Labels: type: bug

#158 fix style
  pyroengine/engine.py
Labels: invalid

#156 Update of the main branch
  Dockerfile
  README.md
  docker-compose.yml
  docs/source/conf.py
  promtail/config.yml
  pyroengine/core.py
  pyroengine/engine.py
  pyroengine/sensors.py
  pyroengine/utils.py
  pyroengine/vision.py
  setup.py
  src/capture.py
  src/run.py
  tests/test_core.py
  tests/test_engine.py
  tests/test_sensors.py
  tests/test_vision.py
Labels: type: new feature
